version: 1.0.{build}

platform:
  - x64

cache:
  - C:\Users\Appveyor\.conan -> conanfile.txt 
  - C:\.conan -> conanfile.txt

install:
  - cmd: echo "Downloading conan..."
  - cmd: pip.exe install conan
  - cmd: conan user # Create the conan data directory
  - cmd: conan --version
  - cmd: conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan || exit 0
  - cmd: echo %PATH%
  
build_script:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: conan install .. -s os=Windows -s arch=x86_64 -s compiler="Visual Studio" -s compiler.runtime=MT -s compiler.version=16 --build missing
  
  - ps: .\activate.ps1
  
  - ps: cat conanbuildinfo.txt
  - ps: cat conaninfo.txt
  - ps: cat activate.bat
  
  - ps: $env:QTVERSION = qmake -v | Select-String -Pattern 'Using Qt version (\d+\.\d+.\d+).*' | % {"$($_.matches.groups[1])"}
  - ps: Write-Output $env:QTVERSION
  
  - ps: $env:QTDIR = $env:CMAKE_PREFIX_PATH.Substring(0, $env:CMAKE_PREFIX_PATH.Length-1)
  - ps: Write-Output $env:QTDIR
  
  - ps: $env:ARCHIVE = "Qt_Static_$env:QTVERSION.zip"
  - ps: Write-Output $env:ARCHIVE