version: 1.0.{build}

platform:
  - x64

cache:
 - C:\Users\Appveyor\.conan -> conanfile.txt 
 - C:\.conan -> conanfile.txt

install:
  - cmd: echo "Downloading conan..."
  - cmd: pip.exe install conan
  - cmd: conan user # Create the conan data directory
  - cmd: conan --version
  - cmd: conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan || exit 0
  - cmd: set PATH=C:\Qt\Tools\mingw530_32\bin;%PATH%
  - cmd: echo %PATH%
  
build_script:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: conan install .. -g virtualenv -s os=Windows -s compiler=gcc -s compiler.version=5.3 -s compiler.libcxx=libstdc++11
  - cmd: activate.bat
  
  - ps: cat conanbuildinfo.txt
  - ps: cat conaninfo.txt
  - ps: cat activate.bat
  
  - ps: $env:QTVERSION = qmake -v | Select-String -Pattern 'Using Qt version (\d+\.\d+.\d+).*' | % {"$($_.matches.groups[1])"}
  - cmd: echo "Qt version: %QTVERSION%"
  
  - cmd: SET QTDIR=%CMAKE_PREFIX_PATH:;=%
  - cmd: echo %QTDIR%
  - ps: $env:ARCHIVE = Qt_Static_$env:QTVERSION.zip
  - ps: Compress-Archive -Path "$env:QTDIR\" -CompressionLevel Optimal -DestinationPath ".\$env:ARCHIVE"


artifacts:
 - path: build\$env:ARCHIVE

